name: banco_amigo
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  firebase_auth: ^4.1.4
  google_fonts: ^3.0.1
  iconsax: ^0.0.8
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  dio: ^4.0.6
  asuka: ^2.0.1+3
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/